# Generated by Django 4.1 on 2022-08-12 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='technician',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=255)),
                ('Prenom', models.CharField(max_length=255)),
                ('Profession', models.CharField(max_length=255)),
                ('Telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('Matricule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Marque', models.CharField(max_length=50)),
                ('Nombre_Cv', models.IntegerField()),
                ('Serie', models.CharField(max_length=50)),
                ('Annee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Service_effectuée', models.CharField(max_length=255)),
                ('date_entrée', models.DateField()),
                ('date_sortie', models.DateField()),
                ('Voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.voiture')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.technician')),
            ],
        ),
    ]
