# Generated by Django 4.0.3 on 2022-08-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_service_id_alter_technician_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='date_entrée',
            new_name='Date_entrée',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='date_sortie',
            new_name='Date_sortie',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='technician',
            new_name='Technician',
        ),
        migrations.RenameField(
            model_name='technician',
            old_name='Id',
            new_name='id',
        ),
    ]
